### ISSUE TITLE
Bug - Simple Temp Calc

### ISSUE THREAD

**Issue by Amythology** [mrtechtroid/python#2]
Just check out the python temp calculator ... noth ath all wolkin'

**Comment by mrtechtroid** [comment]
Thanks For Notifying, I will Look On the Issue Soon.

**Comment by mrtechtroid** [comment]
Hello There, 
The Errors In Orignal File Has Been Fixed
https://github.com/mrtechtroid/python/blob/master/Tools/Simple-Temp-Calc.py
